"""Shared Pydantic models for mcp-tef server and CLI."""

from mcp_tef_models.enums import (
    Classification,
    ConfidenceCategory,
    EmbeddingModelType,
    MCPServerStatus,
    ModelClass,
    SimilarityMethod,
    TestRunStatus,
)
from mcp_tef_models.schemas import (
    DifferentiationIssue,
    DifferentiationRecommendation,
    DifferentiationRecommendationResponse,
    MCPServer,
    MCPServerConfig,
    MCPServerToolsResponse,
    MetricsSummaryResponse,
    ModelSettingsCreate,
    ModelSettingsResponse,
    NormalizedTool,
    OverlapMatrixResponse,
    PaginatedTestCaseResponse,
    PaginatedTestRunResponse,
    RecommendationItem,
    SimilarityAnalysisRequest,
    SimilarityAnalysisResponse,
    SimilarityMatrixResponse,
    SimilarityScore,
    TestCaseCreate,
    TestCaseResponse,
    TestRunExecuteRequest,
    TestRunResponse,
    ToolDefinition,
    ToolDefinitionCreate,
    ToolDefinitionResponse,
    ToolEnrichedResponse,
    ToolPair,
)

__all__ = [
    # Enums
    "Classification",
    "ConfidenceCategory",
    "EmbeddingModelType",
    "MCPServerStatus",
    "ModelClass",
    "SimilarityMethod",
    "TestRunStatus",
    # Schemas
    "DifferentiationIssue",
    "DifferentiationRecommendation",
    "DifferentiationRecommendationResponse",
    "MCPServer",
    "MCPServerConfig",
    "MCPServerToolsResponse",
    "MetricsSummaryResponse",
    "ModelSettingsCreate",
    "ModelSettingsResponse",
    "NormalizedTool",
    "OverlapMatrixResponse",
    "PaginatedTestCaseResponse",
    "PaginatedTestRunResponse",
    "RecommendationItem",
    "SimilarityAnalysisRequest",
    "SimilarityAnalysisResponse",
    "SimilarityMatrixResponse",
    "SimilarityScore",
    "TestCaseCreate",
    "TestCaseResponse",
    "TestRunExecuteRequest",
    "TestRunResponse",
    "ToolDefinition",
    "ToolDefinitionCreate",
    "ToolDefinitionResponse",
    "ToolEnrichedResponse",
    "ToolPair",
]
